name: Cleanup

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Delete old package versions
        uses: actions/delete-package-versions@v5.0.0
        with:
          package-name: 'api-cli'
          package-type: 'npm'
          token: ${{ secrets.PACKAGES_AUTH_TOKEN }}
          min-versions-to-keep: 2