name: Publish
on:
  workflow_call:
    secrets:
      PACKAGES_AUTH_TOKEN:
        required: true
  release:
    types: [released]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all tags
      - name: Publish to github packages
        env:
          PACKAGES_AUTH_TOKEN: ${{ secrets.PACKAGES_AUTH_TOKEN }}
        run: npm publish