name: Create release

# When a tag is pushed, create a release
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all tags

      - name: Create Release for Tag
        id: release_tag
        uses: Akryum/release-tag@a45f9f6a7572682345b87927ea3aacf723225e0b
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGES_AUTH_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          preset: angular # Use conventional-changelog preset

  # trigger_action:
  #   name: Trigger action
  #   runs-on: ubuntu-latest
  #   needs: build
  #   strategy:
  #     matrix:
  #       repo: ['neonmoose/tamer']
  #   steps:
  #     - name: Dispatch event
  #       uses: peter-evans/repository-dispatch@v3
  #       with:
  #         token: ${{ secrets.GH_TOKEN }}
  #         repository: ${{ matrix.repo }}
  #         event-type: trigger_api_cli
  #         client-payload: '{"version": "${{github.ref_name}}"}'